fix(docker): unable to build image using podman (#1901)
* Created a script to update the Dockerfile with every build to 'COPY' package.json files without using --parents to allow use of podman.

Fix bug Unable to build image using podman

* Update docker/Dockerfile to only COPY root package.json once

Co-authored-by: Nick Boldt <nboldt@redhat.com>

* change both Dockerfiles; also include the changed content in this PR

Signed-off-by: Nick Boldt <nboldt@redhat.com>

* Update scripts/update-Dockerfile.sh

* account for latest changes to package.json paths

* update Dockerfile to fit refactors

* add PR check for dirty dockerfiles; update dockerfiles with the latest migrations

Signed-off-by: Nick Boldt <nboldt@redhat.com>

* move to build:dockerfile step

Signed-off-by: Nick Boldt <nboldt@redhat.com>

* put back changes that were force-pushed and lost

Signed-off-by: Nick Boldt <nboldt@redhat.com>

---------

Signed-off-by: Nick Boldt <nboldt@redhat.com>
Co-authored-by: Nick Boldt <nboldt@redhat.com>

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -93,6 +93,12 @@ jobs:
       - name: Run lint
         run: yarn run lint:check --concurrency=75% --affected
 
+      - name: Regenerate dockerfiles
+        run: |
+          yarn run build:dockerfile; if [[ $(git diff --name-only | grep Dockerfile || true) != "" ]]; then \
+            echo "ERROR: Workspace is dirty! Must run 'yarn build:dockerfile' and commit changes!"; exit 1; \
+          fi
+
       - name: Run tests
         run: yarn run test --concurrency=75% --affected
 
