fix(actions): Fix pr docker build
Signed-off-by: Paul Schultz <pschultz@pobox.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -11,7 +11,6 @@ concurrency:
 
 env:
   REGISTRY: quay.io
-  PASSWORD_KEY: QUAY_TOKEN
   USERNAME: ${{ vars.QUAY_USERNAME }}
   IMAGE_NAME: ${{ github.repository }}
 
@@ -52,7 +51,7 @@ jobs:
           echo "recent tags:"; git rev-list --tags --max-count=4
           latest_tag="$(git describe --tags $(git rev-list --tags --max-count=1))"; echo "Got latest tag = $latest_tag"
           echo "latest_tag=$latst_tag" >> "$GITHUB_ENV"
-          git push origin "$latest_tag" || exit 1 # fail if tag already exists 
+          git push origin "$latest_tag" || exit 1 # fail if tag already exists
 
       - name: Publish Image
         if: steps.changesets.outputs.hasChangesets == 'false'
@@ -60,7 +59,7 @@ jobs:
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ env.USERNAME }}
-          password: ${{ secrets[env.PASSWORD_KEY] }}
+          password: ${{ secrets.QUAY_TOKEN }}
           imageName: ${{ env.IMAGE_NAME }}
           imageTags: |
             type=semver,pattern={{version}}
